import nodemailer from "nodemailer";
import { ILead } from "../config/db";

// Lazy transport initialization to ensure the app server never crashes on startup due to network errors.
let transporter: nodemailer.Transporter | null = null;

function getTransporter(): nodemailer.Transporter | null {
  if (transporter) return transporter;

  const host = process.env.SMTP_HOST;
  const port = parseInt(process.env.SMTP_PORT || "2525", 10);
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  if (!user || !pass) {
    // If SMTP details are empty (normal on startup/preview environment), we do not create a transporter.
    return null;
  }

  try {
    transporter = nodemailer.createTransport({
      host,
      port,
      secure: port === 465, // true for 465, false for other ports
      auth: {
        user,
        pass,
      },
    });
    return transporter;
  } catch (error) {
    console.warn("⚠️ Failed to initialize standard email transporter. Notification service is suspended.", error);
    return null;
  }
}

/**
 * Sends a highly styled HTML notification to the CRM Admin whenever a new lead is registered.
 */
export async function sendLeadNotificationEmail(lead: ILead) {
  const adminEmail = process.env.ADMIN_EMAIL || "amruthabethu9@gmail.com";
  const fromEmail = process.env.SMTP_FROM || "alerts@crm.com";

  console.log(`✉️ [Notifier]: Initiating notification for new lead ${lead.name} (${lead.email})`);

  const transport = getTransporter();
  const htmlContent = `
    <div style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; border: 1px solid #e2e8f0; border-radius: 12px; background-color: #fafafa;">
      <div style="text-align: center; margin-bottom: 24px;">
        <span style="font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #4f46e5; background-color: #e0e7ff; padding: 6px 12px; border-radius: 9999px;">
          New Lead Alert
        </span>
        <h2 style="margin-top: 12px; color: #1e293b; font-size: 24px; font-weight: 600;">Website Contact Secured!</h2>
      </div>
      
      <div style="background-color: #ffffff; padding: 20px; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); border: 1px solid #f1f5f9;">
        <table style="width: 100%; border-collapse: collapse;">
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px; width: 35%;"><strong>Lead Name:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;"><strong>${lead.name}</strong></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px;"><strong>Email Address:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;"><a href="mailto:${lead.email}" style="color: #4f46e5; text-decoration: none;">${lead.email}</a></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px;"><strong>Phone Number:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;">${lead.phone || "N/A"}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px;"><strong>Company:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;">${lead.company || "N/A"}</td>
          </tr>
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px;"><strong>Lead Source:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;"><span style="background-color: #f1f5f9; padding: 4px 8px; border-radius: 4px; font-size: 12px;">${lead.source}</span></td>
          </tr>
          <tr>
            <td style="padding: 10px 0; color: #64748b; font-size: 14px;"><strong>Status:</strong></td>
            <td style="padding: 10px 0; color: #0f172a; font-size: 14px;">
              <span style="background-color: #ecfdf5; color: #047857; padding: 4px 8px; border-radius: 4px; font-size: 12px; font-weight: 600;">
                ${lead.status}
              </span>
            </td>
          </tr>
        </table>
        
        <div style="margin-top: 20px; padding-top: 20px; border-top: 1px dashed #e2e8f0;">
          <h4 style="margin: 0 0 10px 0; color: #334155; font-size: 14px;">Initial Notes:</h4>
          <p style="margin: 0; color: #475569; font-size: 13px; font-style: italic; background-color: #f8fafc; padding: 12px; border-radius: 6px; border-left: 3px solid #cbd5e1; line-height: 1.5;">
            ${lead.notes || "No notes supplied by lead."}
          </p>
        </div>
      </div>
      
      <div style="text-align: center; margin-top: 24px; color: #94a3b8; font-size: 11px;">
        <p>This is an automated delivery alert generated by your Client Lead Management CRM.</p>
        <p>© 2026 Mini CRM. All rights reserved.</p>
      </div>
    </div>
  `;

  if (!transport) {
    console.log(`📢 [Notifier Mock Mode]: SMTP is not configured. Suppressing actual email transmission.`);
    console.log(`🚀 [Lead Summary Email Payload for Admin]: Send to ${adminEmail}, Subject: [CRM] New Lead: ${lead.name}`);
    return;
  }

  try {
    const mailOptions = {
      from: `"CRM Notifications" <${fromEmail}>`,
      to: adminEmail,
      subject: `🚨 [New Lead] CRM Alert: ${lead.name} from ${lead.company || "Independent"}`,
      html: htmlContent,
    };

    const info = await transport.sendMail(mailOptions);
    console.log("✅ Email notification dispatched successfully:", info.messageId);
  } catch (error: any) {
    console.error("❌ Failed to dispatch SMTP lead email notification:", error.message);
  }
}
